name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          echo "TWITCH_CHANNEL_NAME: ${{ secrets.TWITCH_CHANNEL_NAME }}"
          docker login --username viktorsjolund --password ${{ secrets.GH_PAT }} ghcr.io
          docker build --build-arg TWITCH_OAUTH_TOKEN=${{ secrets.TWITCH_OAUTH_TOKEN }} --build-arg TWITCH_BOT_NICK=${{ secrets.TWITCH_BOT_NICK }} --build-arg TWITCH_CHANNEL_NAME=${{ secrets.TWITCH_CHANNEL_NAME }} --build-arg SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} --build-arg SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} --build-arg WEB_URI=${{ secrets.WEB_URI }} --build-arg AMQP_ADDR=${{ secrets.AMQP_ADDR }} . --tag ghcr.io/viktorsjolund/stbot:latest
          docker push ghcr.io/viktorsjolund/stbot:latest
