name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username viktorsjolund --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --build-arg TWITCH_OAUTH_TOKEN=${{ vars.TWITCH_OAUTH_TOKEN }} --build-arg TWITCH_BOT_NICK=${{ vars.TWITCH_BOT_NICK }} --build-arg TWITCH_CHANNEL_NAME=${{ vars.TWITCH_CHANNEL_NAME }} --build-arg SPOTIFY_CLIENT_ID=${{ vars.SPOTIFY_CLIENT_ID }} --build-arg SPOTIFY_CLIENT_SECRET=${{ vars.SPOTIFY_CLIENT_SECRET }} --build-arg WEB_URI=${{ vars.WEB_URI }} --build-arg AMQP_ADDR=${{ vars.AMQP_ADDR }} --tag ghcr.io/viktorsjolund/stbot:latest
          docker push ghcr.io/viktorsjolund/stbot:latest
